# Copyright 2026 The Meson Development Team
# SPDX-License-Identifier: Apache-2.0
[project]
project_name = 'embedded_linux_mesa3d'
build_system = 'bazel'

[copyright]
license_name = "embedded_linux_license"
licenses = ["BSD-2-Clause"]
license_texts = ["LICENSE"]

[[config]]
config_name = 'embedded_linux_mesa3d_drivers'

[config.toolchains]
host_toolchains = ["arm_gnu_linux_x86_64"]
build_toolchains = ["arm_gnu_linux_x86_64"]

[config.static_options]
glx = "disabled"
platforms = ""
gallium-drivers = ""
vulkan-drivers = 'gfxstream'
shader-cache = 'disabled'
opengl = false
egl = "disabled"
